# 김태영 케라스

In [1]:
import plaidml.keras
plaidml.keras.install_backend()
from tensorflow.keras import backend
from tensorflow.python.keras import backend
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

In [2]:
seed = 2020
np.random.seed(seed)
tf.random.set_seed(seed)

In [3]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '../dataset/hard_handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '../dataset/hard_handwriting_shape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [4]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu', input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

INFO:plaidml:Opening device "opencl_amd_ellesmere.0"


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 22, 22, 32)        896       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 20, 20, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               819328    
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 387       
Total params: 839,107
Trainable params: 839,107
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

## 모델 학습시키기
- 첫번째 인자 : 훈련데이터셋을 제공할 제네레이터를 지정. 본 예제에서는 앞서 생성한 train_generator으로 지정.
- steps_per_epoch : 한 epoch에 사용한 스텝 수를 지정. 총 45개의 훈련 샘플이 있고 배치사이즈가 3이므로 15 스텝으로 지정.
- epochs : 전체 훈련 데이터셋에 대해 학습 반복 횟수를 지정. 200번을 반복적으로 학습.
- validation_data : 검증데이터셋을 제공할 제네레이터를 지정. 본 예제에서는 앞서 생성한 validation_generator으로 지정.
- validation_steps : 한 epoch 종료 시 마다 검증할 때 사용되는 검증 스텝 수를 지정. 홍 15개의 검증 샘플이 있고 배치사이즈가 3이므로 5 스텝으로 지정.

In [6]:
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/200
15/15 [==============================] - 3s 225ms/step - loss: 1.0858 - acc: 0.5778 - val_loss: 1.2548 - val_acc: 0.4000
Epoch 2/200
15/15 [==============================] - 0s 7ms/step - loss: 0.3969 - acc: 0.8444 - val_loss: 2.3890 - val_acc: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 9ms/step - loss: 0.0987 - acc: 0.9778 - val_loss: 3.1048 - val_acc: 0.4000
Epoch 4/200
15/15 [==============================] - 0s 9ms/step - loss: 0.0082 - acc: 1.0000 - val_loss: 3.6349 - val_acc: 0.3333
Epoch 5/200
15/15 [==============================] - 0s 9ms/step - loss: 0.0027 - acc: 1.0000 - val_loss: 4.1737 - val_acc: 0.3333
Epoch 6/200
15/15 [==============================] - 0s 9ms/step - loss: 0.0013 - acc: 1.0000 - val_loss: 4.4972 - val_acc: 0.3333
Epoch 7/200
15/15 [==============================] - 0s 9ms/step - loss: 7.9057e-04 - acc: 1.0000 - val_loss: 4.6241 - val_acc: 0.3333
Epoch 8/200
15/15 [==============================] - 0s 9ms/step - loss: 6.06

15/15 [==============================] - 0s 10ms/step - loss: 3.0941e-06 - acc: 1.0000 - val_loss: 6.5512 - val_acc: 0.3333
Epoch 62/200
15/15 [==============================] - 0s 10ms/step - loss: 2.9246e-06 - acc: 1.0000 - val_loss: 6.5674 - val_acc: 0.3333
Epoch 63/200
15/15 [==============================] - 0s 9ms/step - loss: 2.8398e-06 - acc: 1.0000 - val_loss: 6.5934 - val_acc: 0.3333
Epoch 64/200
15/15 [==============================] - 0s 9ms/step - loss: 2.6915e-06 - acc: 1.0000 - val_loss: 6.6087 - val_acc: 0.3333
Epoch 65/200
15/15 [==============================] - 0s 9ms/step - loss: 2.5643e-06 - acc: 1.0000 - val_loss: 6.6270 - val_acc: 0.3333
Epoch 66/200
15/15 [==============================] - 0s 9ms/step - loss: 2.4796e-06 - acc: 1.0000 - val_loss: 6.6479 - val_acc: 0.3333
Epoch 67/200
15/15 [==============================] - 0s 10ms/step - loss: 2.3100e-06 - acc: 1.0000 - val_loss: 6.6555 - val_acc: 0.3333
Epoch 68/200
15/15 [==============================] - 0s 1

15/15 [==============================] - 0s 8ms/step - loss: 4.8743e-07 - acc: 1.0000 - val_loss: 7.2855 - val_acc: 0.3333
Epoch 122/200
15/15 [==============================] - 0s 11ms/step - loss: 4.8743e-07 - acc: 1.0000 - val_loss: 7.2900 - val_acc: 0.3333
Epoch 123/200
15/15 [==============================] - 0s 9ms/step - loss: 4.8743e-07 - acc: 1.0000 - val_loss: 7.3002 - val_acc: 0.3333
Epoch 124/200
15/15 [==============================] - 0s 9ms/step - loss: 4.2386e-07 - acc: 1.0000 - val_loss: 7.3111 - val_acc: 0.3333
Epoch 125/200
15/15 [==============================] - 0s 9ms/step - loss: 4.0266e-07 - acc: 1.0000 - val_loss: 7.3177 - val_acc: 0.3333
Epoch 126/200
15/15 [==============================] - 0s 9ms/step - loss: 4.0266e-07 - acc: 1.0000 - val_loss: 7.3274 - val_acc: 0.3333
Epoch 127/200
15/15 [==============================] - 0s 9ms/step - loss: 4.0266e-07 - acc: 1.0000 - val_loss: 7.3391 - val_acc: 0.3333
Epoch 128/200
15/15 [==============================] -

Epoch 181/200
15/15 [==============================] - 0s 9ms/step - loss: 1.2716e-07 - acc: 1.0000 - val_loss: 7.7500 - val_acc: 0.3333
Epoch 182/200
15/15 [==============================] - 0s 9ms/step - loss: 1.2716e-07 - acc: 1.0000 - val_loss: 7.7552 - val_acc: 0.3333
Epoch 183/200
15/15 [==============================] - 0s 9ms/step - loss: 1.2716e-07 - acc: 1.0000 - val_loss: 7.7616 - val_acc: 0.3333
Epoch 184/200
15/15 [==============================] - 0s 9ms/step - loss: 1.2716e-07 - acc: 1.0000 - val_loss: 7.7700 - val_acc: 0.3333
Epoch 185/200
15/15 [==============================] - 0s 9ms/step - loss: 1.2716e-07 - acc: 1.0000 - val_loss: 7.7742 - val_acc: 0.3333
Epoch 186/200
15/15 [==============================] - 0s 9ms/step - loss: 1.0596e-07 - acc: 1.0000 - val_loss: 7.7807 - val_acc: 0.3333
Epoch 187/200
15/15 [==============================] - 0s 9ms/step - loss: 1.0596e-07 - acc: 1.0000 - val_loss: 7.7839 - val_acc: 0.3333
Epoch 188/200
15/15 [====================

In [7]:

print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
acc: 33.33%


In [8]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.000 0.000 1.000]
 [0.000 0.002 0.998]
 [0.358 0.000 0.642]
 [0.000 0.000 1.000]
 [0.002 0.000 0.998]
 [0.001 0.000 0.999]
 [0.000 0.000 1.000]
 [0.396 0.001 0.603]
 [0.000 0.000 1.000]
 [0.000 0.001 0.999]
 [0.181 0.000 0.819]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.951 0.000 0.049]]


In [9]:
for i in range(len(test_generator.labels)):
    print(test_generator.filenames[i], test_generator.labels[i], np.argmax(output[i]))

circle\circle021.png 0 2
circle\circle022.png 0 2
circle\circle023.png 0 2
circle\circle024.png 0 2
circle\circle025.png 0 2
rectangle\rectangle021.png 1 2
rectangle\rectangle022.png 1 2
rectangle\rectangle023.png 1 2
rectangle\rectangle024.png 1 2
rectangle\rectangle025.png 1 2
triangle\triangle021.png 2 2
triangle\triangle022.png 2 2
triangle\triangle023.png 2 2
triangle\triangle024.png 2 2
triangle\triangle025.png 2 0
